### ISSUE TITLE
python-gcm causes MissingRegistration error

### ISSUE THREAD

**Issue by bauerj** [geeknam/python-gcm#84]
This is how I use the library:

    x = self.gcm.plaintext_request(id, {"amount": str(transaction.amount), "address": transaction.to})

When messages didn't reach my phone, I tried to debug this a bit:

The variable `x` contains a NoneType value.

When I used pdb to analyse why it doesn't throw an exception, I found out that it calls `self.raise_error(value)` in base.py:253. But value somehow contains `MissingRegistration` which doesn't get handled by `raise_error`.

This seems to be unlikely as this error should only occur when the request doesn't contain any registration id.

The data that is sent (constructed in base.py:184) contains this value:

    (Pdb) p data
    'data.amount=36.11628274&registration_id=fUxwjeZSVR0%3AAPA91bFfRy0DcYw_gxsMd86FEUdwhR6SrvAV46AHhSeWydnYtLMCvza055jXW-e-j-ETDGGCbVaMBN7TdKR8VvdkqLr_pofWkQcsb1o9FE7kqciPvXxYrxYvp98jZttDZSxe3f8dvuM7&data.address=9GWXR4aD6JSb6DMPxAKH9GeGrBDjhRyxuf'

I don't know if that is how the request data should look like and I don't have any other idea to debug this further.

**Comment by mnemonicflow** [comment]
@bauerj I pressume you are using the pypi version, which is a bit old and will be hopefully be updated soon. That version of python-gcm doesn't handle MissingRegistration error **received from the GCM server** in the raise_error. This problem has been fixed in master branch.
Also in that version there is also a validation made inside the plaintext_request method right at the beginning for the registration_id to be not None, but if your stack trace goes to raise_error it means that the error is coming from the GCM server.

For debugging purposes you can either use a debugger or manually alter the `gcm.py` file that you have installed on your machine and inside the `make_request` method add two log statements for the following two things and tell use the output:
1. Print the request data, add a log statement for the `data` parameter right before the `requests.post` call is made to see exactly what the HTTP request data looks like
2. Print the response data, add a log statement for the `response.content` right after the `requests.post` call is made to see exactly what GCM server sends back.

**Comment by bauerj** [comment]
Hi,

I already did that: The data variable contains what I posted above and the response only contains `Error=MissingRegistration`.

And yes, I'm using the latest version from pypi.

**Comment by mnemonicflow** [comment]
OK. So the above `data` is what you have right before making the HTTP request.
I'm interested in the exact response from the `requests` library not what you get back from python-gcm after processing the response, the response content should contain more information.

**Comment by mnemonicflow** [comment]
@bauerj I think one more thing is happening. Double URL encoding.
Even though I'm not authorized to send the request I've tried to debug the HTTP request using Wireshark and I see this when using as id  `fUxwjeZSVR0%3AAPA91bFfRy0DcYw_gxsMd86FEUdwhR6SrvAV46AHhSeWydnYtLMCvza055jXW-e-j-ETDGGCbVaMBN7TdKR8VvdkqLr_pofWkQcsb1o9FE7kqciPvXxYrxYvp98jZttDZSxe3f8dvuM7`
```
POST /gcm/send HTTP/1.1
Host: gcm-http.googleapis.com
Accept: */*
Authorization: key=123api
Content-Length: 244
User-Agent: python-requests/2.8.0
Accept-Encoding: gzip, deflate
Connection: keep-alive

registration_id=fUxwjeZSVR0%253AAPA91bFfRy0DcYw_gxsMd86FEUdwhR6SrvAV46AHhSeWydnYtLMCvza055jXW-e-j-ETDGGCbVaMBN7TdKR8VvdkqLr_pofWkQcsb1o9FE7kqciPvXxYrxYvp98jZttDZSxe3f8dvuM7&data.address=9GWXR4aD6JSb6DMPxAKH9GeGrBDjhRyxuf&data.amount=36.11628274
```

`%3 = :`
`%3 = %253`
=> Double URL/percent encoding

Can you please manually edit the gcm.py file of your installation and **delete** the following two lines in the make_request method and retry the request:
```
 if not is_json:
            data = urlencode_utf8(data)
```

The `requests` HTTP client library already does URL encoding so I think this might be the problem, let me know.

**Comment by mnemonicflow** [comment]
@bauerj Any news?

**Comment by bauerj** [comment]
Sorry, I was busy earlier today.

Yes, this seems to solve the issue for me.

**Comment by mnemonicflow** [comment]
In that case it seems like the plaintext_request was not tested enough before changing to requests library. 
This problem is fixed in the master branch.

**Comment by bauerj** [comment]
Okay, when will it be fixed on Pypi?

**Comment by mnemonicflow** [comment]
@bauerj I will discuss with @geeknam about the next release, we will do it soon.
